# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .file import *
from .get_file import *
from .provider import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "archive",
  "mod": "index/file",
  "fqn": "pulumi_archive",
  "classes": {
   "archive:index/file:File": "File"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "archive",
  "token": "pulumi:providers:archive",
  "fqn": "pulumi_archive",
  "class": "Provider"
 }
]
"""
)
