// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.archive.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class FileSourceArgs extends com.pulumi.resources.ResourceArgs {

    public static final FileSourceArgs Empty = new FileSourceArgs();

    /**
     * Add this content to the archive with `filename` as the filename.
     * 
     */
    @Import(name="content", required=true)
    private Output<String> content;

    /**
     * @return Add this content to the archive with `filename` as the filename.
     * 
     */
    public Output<String> content() {
        return this.content;
    }

    /**
     * Set this as the filename when declaring a `source`.
     * 
     */
    @Import(name="filename", required=true)
    private Output<String> filename;

    /**
     * @return Set this as the filename when declaring a `source`.
     * 
     */
    public Output<String> filename() {
        return this.filename;
    }

    private FileSourceArgs() {}

    private FileSourceArgs(FileSourceArgs $) {
        this.content = $.content;
        this.filename = $.filename;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FileSourceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FileSourceArgs $;

        public Builder() {
            $ = new FileSourceArgs();
        }

        public Builder(FileSourceArgs defaults) {
            $ = new FileSourceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param content Add this content to the archive with `filename` as the filename.
         * 
         * @return builder
         * 
         */
        public Builder content(Output<String> content) {
            $.content = content;
            return this;
        }

        /**
         * @param content Add this content to the archive with `filename` as the filename.
         * 
         * @return builder
         * 
         */
        public Builder content(String content) {
            return content(Output.of(content));
        }

        /**
         * @param filename Set this as the filename when declaring a `source`.
         * 
         * @return builder
         * 
         */
        public Builder filename(Output<String> filename) {
            $.filename = filename;
            return this;
        }

        /**
         * @param filename Set this as the filename when declaring a `source`.
         * 
         * @return builder
         * 
         */
        public Builder filename(String filename) {
            return filename(Output.of(filename));
        }

        public FileSourceArgs build() {
            $.content = Objects.requireNonNull($.content, "expected parameter 'content' to be non-null");
            $.filename = Objects.requireNonNull($.filename, "expected parameter 'filename' to be non-null");
            return $;
        }
    }

}
