// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.archive.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetFileSource extends com.pulumi.resources.InvokeArgs {

    public static final GetFileSource Empty = new GetFileSource();

    /**
     * Add this content to the archive with `filename` as the filename.
     * 
     */
    @Import(name="content", required=true)
    private String content;

    /**
     * @return Add this content to the archive with `filename` as the filename.
     * 
     */
    public String content() {
        return this.content;
    }

    /**
     * Set this as the filename when declaring a `source`.
     * 
     */
    @Import(name="filename", required=true)
    private String filename;

    /**
     * @return Set this as the filename when declaring a `source`.
     * 
     */
    public String filename() {
        return this.filename;
    }

    private GetFileSource() {}

    private GetFileSource(GetFileSource $) {
        this.content = $.content;
        this.filename = $.filename;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetFileSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetFileSource $;

        public Builder() {
            $ = new GetFileSource();
        }

        public Builder(GetFileSource defaults) {
            $ = new GetFileSource(Objects.requireNonNull(defaults));
        }

        /**
         * @param content Add this content to the archive with `filename` as the filename.
         * 
         * @return builder
         * 
         */
        public Builder content(String content) {
            $.content = content;
            return this;
        }

        /**
         * @param filename Set this as the filename when declaring a `source`.
         * 
         * @return builder
         * 
         */
        public Builder filename(String filename) {
            $.filename = filename;
            return this;
        }

        public GetFileSource build() {
            if ($.content == null) {
                throw new MissingRequiredPropertyException("GetFileSource", "content");
            }
            if ($.filename == null) {
                throw new MissingRequiredPropertyException("GetFileSource", "filename");
            }
            return $;
        }
    }

}
