// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Archive.Outputs
{

    [OutputType]
    public sealed class FileSource
    {
        /// <summary>
        /// Add this content to the archive with `filename` as the filename.
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// Set this as the filename when declaring a `source`.
        /// </summary>
        public readonly string Filename;

        [OutputConstructor]
        private FileSource(
            string content,

            string filename)
        {
            Content = content;
            Filename = filename;
        }
    }
}
