// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface FileSource {
    /**
     * Add this content to the archive with `filename` as the filename.
     */
    content: pulumi.Input<string>;
    /**
     * Set this as the filename when declaring a `source`.
     */
    filename: pulumi.Input<string>;
}

export interface GetFileSource {
    /**
     * Add this content to the archive with `filename` as the filename.
     */
    content: string;
    /**
     * Set this as the filename when declaring a `source`.
     */
    filename: string;
}

export interface GetFileSourceArgs {
    /**
     * Add this content to the archive with `filename` as the filename.
     */
    content: pulumi.Input<string>;
    /**
     * Set this as the filename when declaring a `source`.
     */
    filename: pulumi.Input<string>;
}
