// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Archive.Inputs
{

    public sealed class GetFileSourceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Add this content to the archive with `filename` as the filename.
        /// </summary>
        [Input("content", required: true)]
        public string Content { get; set; } = null!;

        /// <summary>
        /// Set this as the filename when declaring a `source`.
        /// </summary>
        [Input("filename", required: true)]
        public string Filename { get; set; } = null!;

        public GetFileSourceArgs()
        {
        }
        public static new GetFileSourceArgs Empty => new GetFileSourceArgs();
    }
}
